export const PROJECTS_LIST_REQUEST = 'PROJECTS_LIST_REQUEST'
export const PROJECTS_LIST_SUCCESS = 'PROJECTS_LIST_SUCCESS'
export const PROJECTS_LIST_FAIL = 'PROJECTS_LIST_FAIL'

export const PROJECTS_DETAILS_REQUEST = 'PROJECTS_DETAILS_REQUEST'
export const PROJECTS_DETAILS_SUCCESS = 'PROJECTS_DETAILS_SUCCESS'
export const PROJECTS_DETAILS_FAIL = 'PROJECTS_DETAILS_FAIL'
export const PROJECTS_DETAILS_RESET = 'PROJECTS_DETAILS_RESET'

export const FILTER_PROJECTS_REQUEST = 'FILTER_PROJECTS_REQUEST'
export const FILTER_PROJECTS_SUCCESS = 'FILTER_PROJECTS_SUCCESS'
export const FILTER_PROJECTS_FAIL = 'FILTER_PROJECTS_FAIL'
export const FILTER_PROJECTS_RESET = 'FILTER_PROJECTS_RESET'

export const PROJECTS_DELETE_REQUEST = 'PROJECTS_DELETE_REQUEST'
export const PROJECTS_DELETE_SUCCESS = 'PROJECTS_DELETE_SUCCESS'
export const PROJECTS_DELETE_FAIL = 'PROJECTS_DELETE_FAIL'

export const PROJECTS_CREATE_REQUEST = 'PROJECTS_CREATE_REQUEST'
export const PROJECTS_CREATE_SUCCESS = 'PROJECTS_CREATE_SUCCESS'
export const PROJECTS_CREATE_FAIL = 'PROJECTS_CREATE_FAIL'
export const PROJECTS_CREATE_RESET = 'PROJECTS_CREATE_RESET'

export const PROJECTS_UPDATE_REQUEST = 'PROJECTS_UPDATE_REQUEST'
export const PROJECTS_UPDATE_SUCCESS = 'PROJECTS_UPDATE_SUCCESS'
export const PROJECTS_UPDATE_FAIL = 'PROJECTS_UPDATE_FAIL'
export const PROJECTS_UPDATE_RESET = 'PROJECTS_UPDATE_RESET'
